### ISSUE TITLE
Version 1.2.3 Crashes on start.

### ISSUE THREAD

**Issue by tehbeard** [ImCodist/quick-menu#17]
**MC version:** 1.20.6
**Fabric loader:** 0.15.11
**Fabric api:** 0.99.4
**Quick Menu:** 1.2.3
**owo lib:** 0.12.8

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'quickmenu'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:484)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_2487 net.minecraft.class_1799.method_7948()'
	at xyz.imcodist.data.ActionButtonData.fromJSON(ActionButtonData.java:78)
	at xyz.imcodist.other.ActionButtonDataHandler.load(ActionButtonDataHandler.java:41)
	at xyz.imcodist.other.ActionButtonDataHandler.initialize(ActionButtonDataHandler.java:18)
	at xyz.imcodist.QuickMenu.onInitialize(QuickMenu.java:21)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 9 more
```

**Comment by ImCodist** [comment]
Strange. I'll look into this tomorrow.
Sorry for the inconvenience. 😅

**Comment by ImCodist** [comment]
Strange. I am unable to recreate this error.
I've made sure to use the versions of the mods you listed when testing, did you have anything else installed?

It looks like the error has to do with config somehow, but I cannot get it to crash with any variation of config.
You could try deleting your config file. Maybe that would fix it?
And if it does it would be helpful if you sent that config so I can fix it!

If all else fails you could always update owolib and fabric api.
As the mod is confirmed to work on the newest version of both.

For now I am going to mark this as closed.
Feel free to reopen this issue if it persists even after trying my given fixes.
